# Generated by Django 5.2.5 on 2025-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
